export const img_filepath = ``

export const wildlings = [
    {
        name: `Magmutt`,
        image: ``,
        types: [`Fire`,`Earth`],
        hp: `8`,
        power: `16`,
        defense: `9`,
        speed: `7`,
        weaknesses_2x: [`Air`,`Earth`,`Metal`],
        weaknesses_4x: [`Water`],
        resistances_2x: [`Electric`],
        resistances_4x: [],
        ability: `Fuel for the Fire: Immune to Earth-type damage.`,
    },
    {
        name: `Gildgeist`,
        image: ``,
        types: [`Dark`,`Metal`],
        hp: `9`,
        power: `11`,
        defense: `7`,
        speed: `13`,
        weaknesses_2x: [`Light`],
        weaknesses_4x: [`Fire`],
        resistances_2x: [`Dark`,`Electric`,`Poison`],
        resistances_4x: [`Plant`],
        ability: `Dark Cloak: Incoming attacks gain a -2 penalty to hit.`,
    },
    {
        name: `Seraphaeon`,
        image: ``,
        types: [`Light`],
        hp: `5`,
        power: `7`,
        defense: `13`,
        speed: `15`,
        weaknesses_2x: [`Dark`,`Earth`,`Magic`],
        weaknesses_4x: [],
        resistances_2x: [`Dragon`,`Plant`],
        resistances_4x: [],
        ability: `Light Cloak: Light attacks gain an additional +2 bonus to hit.`,
    },
    {
        name: `Dustort`,
        image: ``,
        types: [`Earth`],
        hp: `14`,
        power: `8`,
        defense: `14`,
        speed: `4`,
        weaknesses_2x: [`Metal`,`Plant`,`Water`],
        weaknesses_4x: [],
        resistances_2x: [`Electric`],
        resistances_4x: [],
        ability: `Thirsting Shell: Healed by Water-type attacks. Takes 4 damage at the end of its turns whilst in harsh sunlight.`,
    },
    {
        name: `Whirlaptor`,
        image: ``,
        types: [`Air`],
        hp: `6`,
        power: `13`,
        defense: `6`,
        speed: `15`,
        weaknesses_2x: [`Electric`],
        weaknesses_4x: [],
        resistances_2x: [],
        resistances_4x: [],
        ability: `Flutter Away: Gains an additional +2 to its Evasion.`,
    },
    {
        name: `Scorcharger`,
        image: ``,
        types: [`Fire`,`Electric`],
        hp: `9`,
        power: `15`,
        defense: `9`,
        speed: `7`,
        weaknesses_2x: [`Air`,`Water`],
        weaknesses_4x: [`Earth`],
        resistances_2x: [`Plant`],
        resistances_4x: [],
        ability: `Zippy: Attacks of this Wildling's type(s) gain +1 Priority.`,
    },
    {
        name: `Submareign`,
        image: ``,
        types: [`Water`],
        hp: `7`,
        power: `11`,
        defense: `16`,
        speed: `6`,
        weaknesses_2x: [`Electric`,`Plant`],
        weaknesses_4x: [],
        resistances_2x: [`Fire`],
        resistances_4x: [],
        ability: `Breakthrough: Attacks damage protected Wildlings, but only for 1/2 damage (rounded down).`,
    },
    {
        name: `Arachnogrove`,
        image: ``,
        types: [`Plant`,`Poison`],
        hp: `10`,
        power: `10`,
        defense: `8`,
        speed: `12`,
        weaknesses_2x: [`Air`,`Fire`,`Poison`],
        weaknesses_4x: [],
        resistances_2x: [`Water`],
        resistances_4x: [`Metal`],
        ability: `Leech: Plant-type attacks heal this Wildling for 1/4 of their damage (rounded down).`,
    },
    {
        name: `Gigabex`,
        image: ``,
        types: [`Electric`],
        hp: `7`,
        power: `8`,
        defense: `6`,
        speed: `19`,
        weaknesses_2x: [`Earth`],
        weaknesses_4x: [],
        resistances_2x: [],
        resistances_4x: [],
        ability: `Shocked: Electric attacks used by this Wildling paralyze targets on a base attack roll of 19+.`,
    },
    {
        name: `Boltarum`,
        image: ``,
        types: [`Metal`,`Magic`],
        hp: `14`,
        power: `11`,
        defense: `6`,
        speed: `9`,
        weaknesses_2x: [`Dragon`,`Fire`,`Metal`],
        weaknesses_4x: [],
        resistances_2x: [`Dark`,`Electric`,`Magic`,`Plant`],
        resistances_4x: [],
        ability: `Power-Up: When damaged by a Magic-type attack, this Wildling gains a 1-stage Power boost.`,
    },
    {
        name: `Ascendrago`,
        image: ``,
        types: [`Dragon`,`Air`],
        hp: `9`,
        power: `12`,
        defense: `9`,
        speed: `13`,
        weaknesses_2x: [`Electric`,`Magic`],
        weaknesses_4x: [],
        resistances_2x: [`Air`,`Earth`,`Fire`,`Water`],
        resistances_4x: [],
        ability: `Crowned: Each subsequent attack on the same Wildling deals an incrementing additional 1 damage. This effect resets if this Wildling attacks any others.`,
    },
    {
        name: `Stitchimp`,
        image: ``,
        types: [`Magic`,`Light`],
        hp: `8`,
        power: `13`,
        defense: `11`,
        speed: `8`,
        weaknesses_2x: [`Dark`,`Earth`,`Magic`,`Metal`,`Poison`],
        weaknesses_4x: [],
        resistances_2x: [`Dragon`,`Plant`],
        resistances_4x: [],
        ability: `Archmage: Immune to Magic-type damage. Magic-type damage this Wildling deals is doubled. This Wildling cannot receive more than 1-stage bonuses to any of its stats.`,
    },
    {
        name: `Brimblight`,
        image: ``,
        types: [`Dragon`,`Metal`],
        hp: `19`,
        power: `14`,
        defense: `22`,
        speed: `5`,
        weaknesses_2x: [`Dragon`],
        weaknesses_4x: [],
        resistances_2x: [`Air`,`Dark`,`Earth`,`Electric`,`Plant`,`Poison`,`Water`],
        resistances_4x: [],
        ability: `Horde Guardian: Immune to status effects.`,
    },
    {
        name: `Emberveil`,
        image: ``,
        types: [`Magic`,`Fire`],
        hp: `13`,
        power: `19`,
        defense: `11`,
        speed: `17`,
        weaknesses_2x: [`Air`,`Earth`,`Metal`,`Poison`,`Water`],
        weaknesses_4x: [],
        resistances_2x: [`Plant`],
        resistances_4x: [],
        ability: `Sky Guardian: Immune to Earth-type damage. Heals 4 HP when tagged out.`,
    },
    {
        name: `Emberveil`,
        image: ``,
        types: [`Light`,`Plant`],
        hp: `12`,
        power: `22`,
        defense: `14`,
        speed: `12`,
        weaknesses_2x: [`Air`,`Dark`,`Fire`,`Magic`,`Poison`],
        weaknesses_4x: [],
        resistances_2x: [`Dragon`,`Light`,`Metal`,`Plant`,`Water`],
        resistances_4x: [],
        ability: `Forest Guardian: All attacks gain an additional +1 bonus to hit. Critical hit rate increases by 2.`,
    },
]
